for ii=1:n_bins
    fprintf('%8.0f < LWP < %8.0f & %8.2f & %8.2f & %8.2f & %8.0f \\\\ \n', ...
        round(min_lwp + (bin_size*(ii-1))), ...
        round(min_lwp + (bin_size*ii)), ...
        (poly_reff_aci{ii}(1)*-1), ...
        correlations_reff_beta{ii}(2), ...    
        mdl_lidar_reff{ii}.Rsquared.Ordinary, ...
        numel(data_lidar_corr{ii}))
end


for ii=1:n_bins
    fprintf('%8.0f < LWP < %8.0f & %8.2f & %8.2f & %8.2f & %8.0f \\\\ \n', ...
        round(min_lwp + (bin_size*(ii-1))), ...
        round(min_lwp + (bin_size*ii)), ...
        (poly_Z_aci{ii}(1)*-1), ...
        correlations_Z_beta{ii}(2), ...    
        mdl_lidar_radar{ii}.Rsquared.Ordinary, ...
        numel(data_lidar_corr{ii}))
end